name: aoc2015
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/scottinet/aoc2015

environment:
  sdk: ^3.1.3

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
