name: aoc2015
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/scottinet/aoc2015

environment:
  sdk: ^3.1.3

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.3
  equatable: ^2.0.5
  trotter: ^2.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
